language: python
sudo: required
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - python setup.py test
